name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Elixir ${{matrix.pair.elixir}} / OTP ${{matrix.pair.otp}}
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.10.4
              otp: 21.3.8.24
          - pair:
              elixir: 1.13.4
              otp: 24.3.4.2
            lint: lint
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install Dependencies
        run: mix deps.get --only test

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.get && mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix test
